-- =====================================================================
-- ecommerce - modern e-commerce sample database for PostgreSQL 13+
--
-- The RECOMMENDED sample for new development in this repo. Demonstrates
-- current schema-design practice: identity columns, timestamptz, FKs with
-- explicit ON DELETE, CHECK constraints, jsonb, generated columns,
-- full-text search. Seed data adapted from the Northwind sample by
-- scripts/generate_ecommerce_seed.py.
--
-- This file does NOT create the database. Run ./renew-ecommerce.sh (or
-- .ps1), or manually:
--   createdb ecommerce && psql -d ecommerce -v ON_ERROR_STOP=1 -f ecommerce.sql
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS citext;

BEGIN;

CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------ identity

CREATE TABLE users (
    user_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         citext NOT NULL UNIQUE,
    password_hash text NOT NULL,
    first_name    text NOT NULL,
    last_name     text NOT NULL,
    company_name  text,
    phone         text,
    is_active     boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz
);

CREATE TABLE addresses (
    address_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             bigint NOT NULL REFERENCES users ON DELETE CASCADE,
    label               text NOT NULL DEFAULT 'Primary',
    line1               text NOT NULL,
    line2               text,
    city                text NOT NULL,
    region              text,
    postal_code         text,
    country_code        char(2) NOT NULL,
    is_default_shipping boolean NOT NULL DEFAULT false,
    is_default_billing  boolean NOT NULL DEFAULT false,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_addresses_user ON addresses (user_id);

-- ------------------------------------------------ catalog

CREATE TABLE categories (
    category_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id bigint REFERENCES categories ON DELETE RESTRICT,
    name               text NOT NULL,
    slug               text NOT NULL UNIQUE,
    description        text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_categories_parent ON categories (parent_category_id);

CREATE TABLE products (
    product_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories ON DELETE RESTRICT,
    name        text NOT NULL,
    slug        text NOT NULL UNIQUE,
    description text,
    attributes  jsonb NOT NULL DEFAULT '{}',
    is_active   boolean NOT NULL DEFAULT true,
    search      tsvector GENERATED ALWAYS AS
                (to_tsvector('english', name || ' ' || coalesce(description, ''))) STORED,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_search ON products USING gin (search);

CREATE TABLE product_variants (
    variant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products ON DELETE CASCADE,
    sku        text NOT NULL UNIQUE,
    name       text NOT NULL DEFAULT 'Default',
    price      numeric(12,2) NOT NULL CHECK (price >= 0),
    currency   char(3) NOT NULL DEFAULT 'USD',
    attributes jsonb NOT NULL DEFAULT '{}',
    is_active  boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_variants_product ON product_variants (product_id);

CREATE TABLE product_images (
    image_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products ON DELETE CASCADE,
    url        text NOT NULL,
    alt_text   text,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (product_id, sort_order)
);

-- ------------------------------------------------ inventory

CREATE TABLE inventory (
    variant_id        bigint PRIMARY KEY REFERENCES product_variants ON DELETE CASCADE,
    quantity_on_hand  int NOT NULL CHECK (quantity_on_hand >= 0),
    quantity_reserved int NOT NULL DEFAULT 0 CHECK (quantity_reserved >= 0),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------ fulfillment masters

CREATE TABLE carriers (
    carrier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL UNIQUE,
    phone      text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------ carts

CREATE TABLE carts (
    cart_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint REFERENCES users ON DELETE CASCADE,  -- NULL = guest cart
    session_token uuid NOT NULL DEFAULT gen_random_uuid(),
    status        text NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'converted', 'abandoned')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_carts_active_user ON carts (user_id)
    WHERE status = 'active' AND user_id IS NOT NULL;

CREATE TABLE cart_items (
    cart_id    bigint NOT NULL REFERENCES carts ON DELETE CASCADE,
    variant_id bigint NOT NULL REFERENCES product_variants ON DELETE RESTRICT,
    qty        int NOT NULL CHECK (qty > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (cart_id, variant_id)
);
CREATE INDEX idx_cart_items_variant ON cart_items (variant_id);

-- ------------------------------------------------ orders

CREATE TABLE orders (
    order_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
    order_number      text NOT NULL UNIQUE,
    status            text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'paid', 'processing',
                                        'shipped', 'delivered', 'cancelled')),
    currency          char(3) NOT NULL DEFAULT 'USD',
    subtotal          numeric(12,2) NOT NULL CHECK (subtotal >= 0),
    discount_total    numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    shipping_total    numeric(12,2) NOT NULL DEFAULT 0 CHECK (shipping_total >= 0),
    grand_total       numeric(12,2) NOT NULL CHECK (grand_total >= 0),
    -- ship-to snapshot: survives later edits to the user's saved addresses
    ship_name         text,
    ship_line1        text,
    ship_city         text,
    ship_region       text,
    ship_postal_code  text,
    ship_country_code char(2),
    ordered_at        timestamptz NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_ordered_at ON orders (ordered_at);

CREATE TABLE order_items (
    order_id     bigint NOT NULL REFERENCES orders ON DELETE CASCADE,
    variant_id   bigint NOT NULL REFERENCES product_variants ON DELETE RESTRICT,
    -- snapshots: survive later catalog edits
    product_name text NOT NULL,
    sku          text NOT NULL,
    unit_price   numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    qty          int NOT NULL CHECK (qty > 0),
    discount     numeric(4,3) NOT NULL DEFAULT 0 CHECK (discount >= 0 AND discount <= 1),
    line_total   numeric(12,2) GENERATED ALWAYS AS
                 (round(unit_price * qty * (1 - discount), 2)) STORED,
    PRIMARY KEY (order_id, variant_id)
);
CREATE INDEX idx_order_items_variant ON order_items (variant_id);

CREATE TABLE order_status_history (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   bigint NOT NULL REFERENCES orders ON DELETE CASCADE,
    status     text NOT NULL
               CHECK (status IN ('pending', 'paid', 'processing',
                                 'shipped', 'delivered', 'cancelled')),
    note       text,
    changed_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_order_status_history_order ON order_status_history (order_id);

CREATE TABLE payments (
    payment_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     bigint NOT NULL REFERENCES orders ON DELETE CASCADE,
    amount       numeric(12,2) NOT NULL CHECK (amount >= 0),
    currency     char(3) NOT NULL DEFAULT 'USD',
    provider     text NOT NULL CHECK (provider IN ('card', 'paypal', 'bank_transfer')),
    provider_ref text,  -- gateway reference only; never store card data (PCI)
    status       text NOT NULL
                 CHECK (status IN ('pending', 'authorized', 'captured',
                                   'failed', 'refunded')),
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_order ON payments (order_id);

CREATE TABLE shipments (
    shipment_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL REFERENCES orders ON DELETE CASCADE,
    carrier_id      bigint NOT NULL REFERENCES carriers ON DELETE RESTRICT,
    tracking_number text,
    shipped_at      timestamptz,
    delivered_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CHECK (delivered_at IS NULL OR shipped_at IS NULL OR delivered_at >= shipped_at)
);
CREATE INDEX idx_shipments_order ON shipments (order_id);
CREATE INDEX idx_shipments_carrier ON shipments (carrier_id);

-- Append-only stock ledger. Snapshot lives in inventory; the seed keeps
-- sum(quantity_delta) = inventory.quantity_on_hand for every variant.
CREATE TABLE inventory_movements (
    movement_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id     bigint NOT NULL REFERENCES product_variants ON DELETE CASCADE,
    quantity_delta int NOT NULL CHECK (quantity_delta <> 0),
    reason         text NOT NULL
                   CHECK (reason IN ('restock', 'sale', 'return', 'adjustment')),
    order_id       bigint REFERENCES orders ON DELETE SET NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_inventory_movements_variant ON inventory_movements (variant_id);
CREATE INDEX idx_inventory_movements_order ON inventory_movements (order_id);

-- ------------------------------------------------ updated_at triggers

CREATE TRIGGER trg_users_updated            BEFORE UPDATE ON users            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_addresses_updated        BEFORE UPDATE ON addresses        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_categories_updated       BEFORE UPDATE ON categories       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_products_updated         BEFORE UPDATE ON products         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_product_variants_updated BEFORE UPDATE ON product_variants FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_inventory_updated        BEFORE UPDATE ON inventory        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_carts_updated            BEFORE UPDATE ON carts            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_cart_items_updated       BEFORE UPDATE ON cart_items       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_orders_updated           BEFORE UPDATE ON orders           FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------ seed data

-- SEED:BEGIN
-- (generated by scripts/generate_ecommerce_seed.py - do not edit by hand)

-- ------------------------------------------------ sequence resync
-- Seed rows insert explicit ids (GENERATED BY DEFAULT allows this); move
-- each identity sequence past the seeded maximum.

SELECT setval(pg_get_serial_sequence('users',            'user_id'),     (SELECT coalesce(max(user_id),     0) + 1 FROM users),            false);
SELECT setval(pg_get_serial_sequence('addresses',        'address_id'),  (SELECT coalesce(max(address_id),  0) + 1 FROM addresses),        false);
SELECT setval(pg_get_serial_sequence('categories',       'category_id'), (SELECT coalesce(max(category_id), 0) + 1 FROM categories),       false);
SELECT setval(pg_get_serial_sequence('products',         'product_id'),  (SELECT coalesce(max(product_id),  0) + 1 FROM products),         false);
SELECT setval(pg_get_serial_sequence('product_variants', 'variant_id'),  (SELECT coalesce(max(variant_id),  0) + 1 FROM product_variants), false);
SELECT setval(pg_get_serial_sequence('product_images',   'image_id'),    (SELECT coalesce(max(image_id),    0) + 1 FROM product_images),   false);
SELECT setval(pg_get_serial_sequence('carriers',         'carrier_id'),  (SELECT coalesce(max(carrier_id),  0) + 1 FROM carriers),         false);
SELECT setval(pg_get_serial_sequence('carts',            'cart_id'),     (SELECT coalesce(max(cart_id),     0) + 1 FROM carts),            false);
SELECT setval(pg_get_serial_sequence('orders',           'order_id'),    (SELECT coalesce(max(order_id),    0) + 1 FROM orders),           false);

COMMIT;
